patch sol2 to not fail in C++20 mode
on mac xcode/AppleClang, due to const char*/const char8_t*
incompatibility and the fact that u8"string" literals are now
const char8*.

error: invalid conversion from 'const char8_t*' to 'const char*'
(and friends)